### ISSUE TITLE
AssertionError: False is not true

### ISSUE THREAD

**Issue by YanWang2014** [gdlg/pytorch_compact_bilinear_pooling#3]
Hi,
I am back again. When running the test.py, I got the following error
`  File "test.py", line 69, in test_gradients
    self.assertTrue(torch.autograd.gradcheck(cbp, (x,y), eps=1))
AssertionError: False is not true`

What does this mean?

**Comment by gdlg** [comment]
Hi Yan,

torch.autograd.gradcheck  fails because the gradients are not strictly reentrant however the differences are very small to the order of 10⁻⁹.

I have narrowed down the issue to the call to scatter_add in CountSketchFn_forward.
The test pass if you force scatter_add to work on the CPU.
In the function, CountSketchFn_forward, replacing:
```
out = x.new(*out_size).zero_()
return out.scatter_add_(-1, h, xs)
```
with a CPU version:
```
out = x.new(*out_size).zero_().cpu()
return out.scatter_add_(-1, h.cpu(), xs.cpu()).cuda()
```
then all the tests pass successfully.

The differences are so small that I think that it is safe to ignore this problem however it will be nice to find a solution. I think that the problem is due to rounding differences depending 
on the non-deterministic order of execution of the scatter_add on the GPU.

**Comment by YanWang2014** [comment]
Yes, the tests pass successfully after using CPU. Thank you!
