### ISSUE TITLE
The miss of Rfft

### ISSUE THREAD

**Issue by PeiqinZhuang** [gdlg/pytorch_compact_bilinear_pooling#5]
When I run the test module, it indicates that the module of pytorch_fft of fft in autograd  does not have attribute of Rfft.  What version of pytorch_fft should I install to  fit this code?

**Comment by gdlg** [comment]
You need to use the latest version available on Github. The version in Pypi is a bit old and doesn't have the Rfft.

Also when running the tests, you should notice that the gradient test fails. It’s expected because PyTorch gradcheck checks if the gradients are reentrant and the GPU computation are not quite reentrant due to rounding errors however it doesn’t affect the correctness of the computation.

**Comment by xingdi1990** [comment]
I installed the latest 0.14 version of pytorch_fft. However, I still met such a problem. Did you solve it?
 @PeiqinZhuang

**Comment by gdlg** [comment]
@DetionDX The Pypi version of PyTorch has not been updated with the support for rfft. Try to use the latest version of pytorch_fft on Github. I can try to ask the pytorch_fft maintainer to update the Pypi version.

**Comment by xingdi1990** [comment]
Hi, @gdlg, thanks a lot for your response.  I installed the latest version from pytorch_fft github. However, it shows a new issue: 

  File "<stdin>", line 1, in <module>
  File "CompactBilinearPooling.py", line 6, in <module>
    import pytorch_fft.fft.autograd as afft
  File "build/bdist.linux-x86_64/egg/pytorch_fft/__init__.py", line 1, in <module>
    
  File "build/bdist.linux-x86_64/egg/pytorch_fft/fft/__init__.py", line 1, in <module>
    
  File "build/bdist.linux-x86_64/egg/pytorch_fft/fft/fft.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pytorch_fft/_ext/th_fft/__init__.py", line 3, in <module>
    
ImportError: No module named _th_fft

**Comment by gdlg** [comment]
I have not come across that error before. Did you install pytorch_fft using the setup.py? It sounds like you are missing pytorch_fft shared library in your Python search path.

**Comment by pangjh3** [comment]
@gdlg I try python setup.py install but still have the sam problem? What can I do?

**Comment by gdlg** [comment]
@SkyFlyboy , @DetionDX , I have updated my version of pytorch_fft and now I can see the problem. I was using pytorch_fft at commit c03132a0adecbc24030d8f4f12067a04e00b04f1 and it works. I guess that the problem was introduced later. I can see that there is already an issue for that at locuslab/pytorch_fft#26

**Comment by gdlg** [comment]
The problem has been fixed in pytorch_fft and the Pypi version of pytorch_fft has also been updated to include Rfft and its variations.
