### ISSUE TITLE
The value in ComplexMultiply_backward function

### ISSUE THREAD

**Issue by kaiyuyue** [gdlg/pytorch_compact_bilinear_pooling#6]
Hi @gdlg, thanks for this nice work. I'm confused about the `backward` procedure of complex multiplication. So I hope you can help me to figure it out.

In forward, 
```
Z = XY = (Rx + i * Ix)(Ry + i * Iy) = (RxRy - IxIy) + i * (IxRy + RxIy) = Rz + i * Iz
```
In backward, according the chain rule, it will has
```
grad_(L/X) = grad_(L/Z) * grad(Z/X)
           = grad_Z * Y
           = (R_gz + i * I_gz)(Ry + i * Iy)
           = (R_gzRy - I_gzIy) + i * (I_gzRy + R_gzIy)
``` 
So, why is this [line](https://github.com/gdlg/pytorch_compact_bilinear_pooling/blob/20934a5cc8ecb4acb4dba3074f523505d639352b/compact_bilinear_pooling.py#L118) implemented by using the `value = 1` for real part and `value = -1` for image part?

Is there something wrong in my thoughts? Thanks.

**Comment by gdlg** [comment]
Hi @KaiyuYue , thank you for diving into the code and checking its correctness.

I believe that the code is actually correct. In your calculation, you are assuming that the differentiation of a holomorphic function works in the same way as for real-valued function however the correct way is not as straightforward.

To get to the correct result, you need to either use Wirtinger derivatives (https://en.wikipedia.org/wiki/Wirtinger_derivatives#Chain_rule) or treat all the functions as function of 2 real-valued variables instead of 1 complex one. In the second case, the main difference is that you have to differentiate w.r.t to Re(x) and Im(x) separately.

Here is a not-so-short proof using Wirtinger derivatives:
If we write L = f(z) and z = g(x,y) = x * y

The Wirtinger derivatives of g w.r.t x are:
![My Formula](http://latex.codecogs.com/gif.latex?%5Cfrac%7B%5Cpartial%20g%7D%7B%5Cpartial%20x%7D%20%3D%20i%20Im(y)%20%5Ctextbf%7B%20and%20%7D%20%5Cfrac%7B%5Cpartial%20g%7D%7B%5Cpartial%20%5Cbar%20x%7D%20%3D%20Re(y)%20%5Ctextbf%7B%20(and%20also%20%7D%20%5Cfrac%7B%5Cpartial%20%5Cbar%20g%7D%7B%5Cpartial%20x%7D%20%3D%20Re(y)%20%5Ctextbf%7B%20and%20%7D%20%5Cfrac%7B%5Cpartial%20%5Cbar%20g%7D%7B%5Cpartial%20%5Cbar%20x%7D%20%3D%20-%20i%C3%97Im(y)%20%5Ctextbf%7B)%7D)

We can compute dL/dRe(x) and dL/dIm(x):

![My Formula](http://latex.codecogs.com/gif.latex?%5Cbegin%7Balign*%7D%0A%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20Re(x)%7D%20%26%20%3D%20i%20%5Cleft(%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20x%7D%20%2B%20%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20%5Cbar%20x%7D%5Cright)%20%5Cquad%20%26%20%5Ctextbf%7B(by%20def.%20of%20Wirtinger%20derivatives)%7D%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%26%20%3D%20i%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%5Ccdot%20%5Cfrac%7B%5Cpartial%20g%7D%7B%5Cpartial%20x%7D%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%5Ccdot%20%5Cfrac%7B%5Cpartial%20%5Cbar%20g%7D%7B%5Cpartial%20x%7D%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%5Ccdot%20%5Cfrac%7B%5Cpartial%20g%7D%7B%5Cpartial%20%5Cbar%20x%7D%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%5Ccdot%20%5Cfrac%7B%5Cpartial%20%5Cbar%20g%7D%7B%5Cpartial%20%5Cbar%20x%7D%20%5Cquad%20%26%20%5Ctextbf%7B(by%20the%20chain%20rule)%7D%0A%5Cend%7Balign*%7D)

Then substituting and regrouping:
![My Formula](http://latex.codecogs.com/gif.latex?%5Cbegin%7Balign*%7D%0A%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20Re(x)%7D%20%26%20%3D%20i%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%5Ccdot%20Im(y)%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%5Ccdot%20Re(y)%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%5Ccdot%20Re(y)%20-%20i%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%5Ccdot%20Im(y)%20%5Cquad%20%26%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%26%20%3D%20%5Cleft(%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%5Cright)%20%5Ccdot%20Re(y)%20%2B%20i%20%5Cleft(%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20-%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%5Cright)%20%5Ccdot%20Im(y)%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%26%20%3D%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20Re(z)%7D%20%5Ccdot%20Re(y)%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20Im(z)%7D%20%5Ccdot%20Im(y)%20%5Cquad%20%26%20%5Ctextbf%7B(by%20def.%20of%20Wirtinger%20derivatives)%7D%20%5C%5C%0A%5Cend%7Balign*%7D)

Thus `grad_X_re = torch.addcmul(grad_Z_re * Y_re,  1, grad_Z_im, Y_im)`

Similarly:
![My Formula](http://latex.codecogs.com/gif.latex?%5Cbegin%7Balign*%7D%0A%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20Im(x)%7D%20%26%20%3D%20i%20%5Cleft(%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20x%7D%20-%20%5Cfrac%7B%5Cpartial%20L%7D%7B%5Cpartial%20%5Cbar%20x%7D%5Cright)%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%26%20%3D%20-%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%5Ccdot%20Im(y)%20%2B%20i%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%5Ccdot%20Re(y)%20-%20i%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%5Ccdot%20Re(y)%20-%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20%5Ccdot%20Im(y)%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%26%20%3D%20i%20%5Cleft(%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%20-%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%5Cright)%20%5Ccdot%20Re(y)%20-%20%5Cleft(%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20z%7D%20%2B%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20%5Cbar%20z%7D%5Cright)%20%5Ccdot%20Im(y)%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%26%20%3D%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20Im(z)%7D%20%5Ccdot%20Re(y)%20-%20%5Cfrac%7B%5Cpartial%20f%7D%7B%5Cpartial%20Re(z)%7D%20%5Ccdot%20Im(y)%0A%0A%5Cend%7Balign*%7D)

Thus `grad_X_im = torch.addcmul(grad_Z_im * Y_re, -1, grad_Z_re, Y_im)`

Assuming that the calculus above is correct, the code should be as well. I will add a gradcheck test to prove the correctness of the multiplication.

This backward function is actually not used in the computation of the compact bilinear pooling gradient because I tried to rearrange the computation of the multiplication and FFT gradients to decrease the memory footprint however the formula is the same.

**Comment by kaiyuyue** [comment]
Very inspired. Thanks for correcting my errors.

**Comment by kaiyuyue** [comment]
The backward function actually is not used means the memory used of the part is the same as that of this way?
```python
import pytorch_fft.fft.autograd as afft

sketch_x = CountSketchFn_forward(h1, s1, output_size, x)
sketch_y = CountSketchFn_forward(h2, s2, output_size, y)

x_re, x_im = afft.Fft()(sketch_x, sketch_x.new(*sketch_x.size()).zero_())
y_re, y_im = afft.Fft()(sketch_y, sketch_y.new(*sketch_y.size()).zero_())

prod_re, prod_im = x_re.mul(y_re), x_im.mul(y_im)
```

**Comment by gdlg** [comment]
I am not entirely sure what you mean.
In the current implementation, I don’t use the backward function [ComplexMultiply_backward](https://github.com/gdlg/pytorch_compact_bilinear_pooling/blob/20934a5cc8ecb4acb4dba3074f523505d639352b/compact_bilinear_pooling.py#L118) however I have interleaved the FFTs and part of the complex multiply [here](https://github.com/gdlg/pytorch_compact_bilinear_pooling/blob/20934a5cc8ecb4acb4dba3074f523505d639352b/compact_bilinear_pooling.py#L188) and [there](https://github.com/gdlg/pytorch_compact_bilinear_pooling/blob/20934a5cc8ecb4acb4dba3074f523505d639352b/compact_bilinear_pooling.py#L202) to compute grad_x then grad_y and avoid having a bench of temporaries.
I have found that it is difficult to really benchmark the use of memory in PyTorch so I am not really sure how much memory was saved.

Regarding your snippet,
`x_re, x_im = afft.Fft()(sketch_x, sketch_x.new(*sketch_x.size()).zero_())`
It is more efficient to use Rfft which exploits the symmetry of the FFT of a real-valued function and return an array half the size of the output of Fft. This saves both memory and computations.

`prod_re, prod_im = x_re.mul(y_re), x_im.mul(y_im)`
This is not the true complex multiplication but I am not really sure that it matters in the implementation of compact bilinear pooling.

**Comment by kaiyuyue** [comment]
<img width="331" alt="machi 2018-02-23 00-31-46" src="https://user-images.githubusercontent.com/19852297/36550742-fa3852f2-1830-11e8-9843-d7026ff53fae.png">

Here is the original TS algorithm used in paper of Compact Bilinear Pooling. The last procedure said that doing the `element-wise multiplication` between two FFT outputs. So does it mean the true complex multiplication or in this way `prod_re, prod_im = x_re.mul(y_re), x_im.mul(y_im)`?

**Comment by gdlg** [comment]
Thanks @KaiyuYue . I didn’t spot that in the paper. I will correct the implementation to match the original algorithm.

**Comment by gdlg** [comment]
Actually I think that the implementation is correct.

The `where the ◦ denotes element-wise multiplication.` denotes the fact the multiplication should be element-wise with respect to the array however it is still a complex multiplication.

This multiplication stems from 3.2 `Moreover, one can show that Ψ(x ⊗ y, h, s) = Ψ(x, h, s) ∗ Ψ(y, h, s), i.e. the count sketch of two vectors’ outer product is the convolution of individual’s count sketch`

The Caffe [implementation](https://github.com/gy20073/compact_bilinear_pooling/blob/60db56d88b5eda346eaf450b1c2c2da634cf457f/caffe-20160312/src/caffe/layers/compact_bilinear_layer.cu#L309) by Gao et al. is also using a complex multiplication.

**Comment by kaiyuyue** [comment]
Oh! My bad. Thanks.

**Comment by KaiyuYue** [comment]
Is there any possible to speed up these part code with high dimensional random vector `h`?
